### ISSUE TITLE
Add to HTML and front page

### ISSUE THREAD

**Issue by allyharrison** [allyharrison/Agile-Web-Dev-CITS5505#18]
Fill out parts of existing HTML that aren't complete
- [ ] Add footer
- [ ] Add buttons to navbar, and list options as list underneath:
    - [ ] Recipes (ie breakfast, lunch, dinner)
    - [ ] Cuisine (ie Indian, Chinese, Italian)
    - [ ] Making a request - this can be part of the menu and/or a persistent button on the other pages

**Comment by St-d603** [comment]
For the HTML are we going to make a new HTML page for these selection? I feel like this will enable the web page to look more aesthetic and UI friendly. For example, 

**In the nav bar drop-down**
<li class="dropdown">
            <a href="cuisine.html">CUISINE TYPE</a> _(this would be were we link the new pages)_
          <div class="dropdown-content">
            <a href="#">ASIAN</a>
              <a href="#">INDIAN</a>
              <a href="#">MEXICAN</a>
              <a href="#">EUROPEAN</a>
         </li>

**Comment by allyharrison** [comment]
Yeah I agree - I think that would be good, and it's probably more sensible from a UI perspective. Makes sense to put that stuff on a new page rather than adding a too many extra options in the menu.
