### ISSUE TITLE
Basic CSS

### ISSUE THREAD

**Issue by allyharrison** [allyharrison/Agile-Web-Dev-CITS5505#5]
Small task, content to be updated throughout the project life cycle
CSS to follow up 
With HTML and Figma layout, start basic CSS creation and alignment. 
potential library research

**Comment by St-d603** [comment]
I think https://getbootstrap.com/ would be ideal to use.

**Comment by allyharrison** [comment]
Yeah I think we should def use a framework like Bootstrap, we skimmed over it pretty quickly in the last meeting but I reckon it'll be way easier than trying style things with vanilla CSS.
It'll make it much easier if we can just add in buttons and navbars etc that are styled by default.
A web dev friend of mine suggested Bulma https://bulma.io/ as well, it offers stuff like dark mode and is based off flexbox, but I think Bootstrap will be great too if everyone is keen on that - it seems to offer a lot of functionality.
